### ISSUE TITLE
Rendering of description property in Field base class missing

### ISSUE THREAD

**Issue by ghost** [carl-newton/bootstrap-wtf#2]
Each FieldType in WTForms provide a description property for use as help text. Details can be found here - http://wtforms.readthedocs.org/en/latest/fields.html#the-field-base-class

I'll be be happy to submit a pull request to implement this change.

**Comment by carlnewton** [comment]
Well spotted. Yes, please do. There's a "help-block" class used in bootstrap forms for this.

**Comment by carlnewton** [comment]
I've added support for the description parameter.

Thanks
